services:
    pantheon-dashboard:
        build: .
        image: pantheon-dashboard
        container_name: pantheon-dashboard
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
            NODE_ENV: production
        # networks:
        #     - webservices
        volumes:
            - uploads:/pantheon-dashboard/public/uploads
            - database:/pantheon-dashboard/src/app/data
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "-q",
                    "--spider",
                    "http://localhost:3000/api/health",
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        labels:
            - deunhealth.restart.on.unhealthy=true

# networks:
#     webservices:
#         external: true

volumes:
    uploads:
    database:
