services:
    pantheon-dashboard:
        build: .
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_BASE: "http://localhost:3000"
        volumes:
            - uploads:/pantheon-dashboard/public/uploads
            - database:/pantheon-dashboard/src/app/data

volumes:
    uploads:
    database:
